# Build settings
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-seo-tag

# Site settings
title: "Morgan Carroll"
tagline: A place for blogs, dogs, and whatever else I can think of
description: > # this means to ignore newlines until "email:"
   Senior AI Engineer at IBM, Dog Mom, Tinkerer

email:
logo: "/assets/images/ml_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover:

name: 'Morgan Carroll'
author: 'Morgan Carroll'
author_image: "/assets/images/ml_logo.jpg"

paginate:	5

url: "http://themorgan.ai" # the base hostname & protocol for your site
baseurl: ""

google_analytics: 159138432-1

# social icons and sharing options
social:
  - icon:	github
    url:	https://github.com/modcarroll
    desc:	Fork me on github
    share_url: 
    share_title: 
    share_link: 

  - icon:	facebook
    url:	
    desc:	
    share_url: https://www.facebook.com/sharer/sharer.php
    share_title: 
    share_link: ?u=

  - icon:	linkedin
    url:	https://www.linkedin.com/in/modcarroll
    desc:	Link up on LinkedIn
    share_url: https://www.linkedin.com/sharing/share-offsite/
    share_title: 
    share_link: ?url=

  - icon:	instagram
    url:
    desc:	
    share_url: 
    share_title: 
    share_link: 

  - icon: youtube
    url:

  - icon: twitch
    url:

theme: jekyll-theme-cayman
