# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Morgan Langlais"
description: > # this means to ignore newlines until "email:"
   Software Developer and Customer Success Manager at IBM

email: morgandlanglais@gmail.com
#blog logo
logo: "/assets/images/ml_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/dogs-wallpaper.png"

name: 'Morgan Langlais'
author: 'Morgan Langlais'
author_image: "/assets/images/ml_logo.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@zephyr3c33'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/zephyr3c33
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/modlanglais
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	linkedin
    url:	https://www.linkedin.com/in/morganlanglais
    desc:	Link up on LinkedIn
    share_url:
    share_title:
    share_link:
