# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Morgan Langlais"
description: > # this means to ignore newlines until "email:"
   Software Engineer and Data & AI Customer Success Manager at IBM

email: morgandlanglais@gmail.com
logo: "/assets/images/ml_logo.jpg"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/dogs-wallpaper.png"

name: 'Morgan Langlais'
author: 'Morgan Langlais'
author_image: "/assets/images/ml_logo.jpg"

paginate:	5

url: "http://myblog.***.***" # the base hostname & protocol for your site
baseurl: ""
twitter_handle: '@zephyr3c33'

google_analytics: 159138432-1

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/zephyr3c33
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/modlanglais
    desc:	Fork me on github
    share_url: 
    share_title: 
    share_link: 

  - icon:	facebook
    url:	
    desc:	
    share_url: https://www.facebook.com/sharer/sharer.php
    share_title: 
    share_link: ?u=

  - icon:	linkedin
    url:	https://www.linkedin.com/in/morganlanglais
    desc:	Link up on LinkedIn
    share_url: https://www.linkedin.com/sharing/share-offsite/
    share_title: 
    share_link: ?url=

  - icon:	instagram
    url:	https://www.instagram.com/modlanglais/
    desc:	
    share_url: 
    share_title: 
    share_link: 

  - icon: youtube
    url: https://www.youtube.com/channel/UCUVGe5tXAPQaqan3WNga5yg

  - icon: twitch
    url: https://www.twitch.tv/zephyr3c33

theme: jekyll-theme-cayman